Disallow the next button when the intervention has not been interacted with
sandboxnu/vocab-buddy pull request #47
Opened 2021-02-08 02:35 UTC by jrosen081

This fixes the issue that @stefan-philip reported.

2021-02-08 02:52 UTC, cindy1u0 approved these changes
LGTM ~

2021-02-08 02:52 UTC, cindy1u0 commented on frontend/src/pages/Interventions/FirstActivity.tsx
> +                canBeShown
ig technically we don't really need canBeShown for first activity and fourth activity but I think it's okay to just leave it

2021-02-08 03:03 UTC, stefan-philip requested changes
On the yes-or-no activity, when you select yes or no the prompt is played again

2021-02-08 03:13 UTC, jrosen081 commented
@stefan-philip Good catch. This should be fixed now

2021-02-09 03:35 UTC, stefan-philip approved these changes
Awesome!

2021-02-09 03:40 UTC, merged